### ISSUE TITLE
Question about retrieval corpus

### ISSUE THREAD

**Issue by EileenWang1228** [ase-decom/ASE22_DECOM#1]
您好，论文里面说“Specifically, we first take the training set of the benchmark dataset as the retrieval corpus”。就是把数据集的训练集作为检索库对吧。但是对于训练集中的某一条code来说，它的similar code是怎么得到的呢？是选择除了它本身之外最相似的那个吗？非常期望得到您的回复，十分感谢。

**Comment by ase-decom** [comment]
Thanks for your attention to our work.
1.yes, we use the training set as the retrieval corpus.
2.yes, we choose the second-ranked similar code when training.
